
def recherche_vue(id_inao):
    match id_inao:
        case 1179:
            return "matview_abondance_1179"
        case 480:
            return "matview_banon_480"
        case 404:
            return "matview_beaufort_404"
        case 405:
            return "matview_bleu_auvergne_405"
        case 406:
            return "matview_bleu_causses_406"
        case 407:
            return "matview_bleu_gex_407"
        case 442:
            return "matview_bleu_vercors_442"
        case 408:
            return "matview_brie_meaux_408"
        case 409:
            return "matview_brie_melun_409"
        case 784:
            return "matview_brillat_savarin_784"
        case 1527:
            return "matview_brocciu_1527"
        case 411:
            return "matview_camembert_411"
        case 412:
            return "matview_cantal_412"
        case 413:
            return "matview_chabichou_413"
        case 415:
            return "matview_chaource_415"
        case 657:
            return "matview_charolais_657"
        case 416:
            return "matview_chavignol_416"
        case 472:
            return "matview_chevrotin_472"
        case 414:
            return "matview_comte_414"
        case 554:
            return "matview_emmental_est_central_554"
        case 498:
            return "matview_emmental_savoie_498"
        case 417:
            return "matview_epoisses_417"
        case 418:
            return "matview_fourme_ambert_418"
        case 471:
            return "matview_fourme_montbrison_471"
        case 857:
            return "matview_gruyere_857"
        case 419:
            return "matview_laguiole_419"
        case 420:
            return "matview_langres_420"
        case 421:
            return "matview_livarot_421"
        case 596:
            return "matview_maconnais_596"
        case 422:
            return "matview_maroilles_422"
        case 423:
            return "matview_mont_dor_423"
        case 445:
            return "matview_morbier_445"
        case 424:
            return "matview_munster_424"
        case 425:
            return "matview_neuchatel_425"
        case 426:
            return "matview_ossau_iraty_426"
        case 444:
            return "matview_pelardon_444"
        case 662:
            return "matview_perail_662"
        case 427:
            return "matview_picodon_427"
        case 428:
            return "matview_pont_leveque_428"
        case 429:
            return "matview_pouligny_429"
        case 763:
            return "matview_raclette_763"
        case 430:
            return "matview_reblochon_430"
        case 666:
            return "matview_rigotte_666"
        case 431:
            return "matview_rocamadour_431"
        case 432:
            return "matview_roquefort_432"
        case 669:
            return "matview_saint_marcelin_669"
        case 433:
            return "matview_saint_nectaire_433"
        case 434:
            return "matview_sainte_maure_touraine_434"
        case 435:
            return "matview_salers_435"
        case 436:
            return "matview_selles_sur_cher_436"
        case 1046:
            return "matview_soumaintrain_1046"
        case 476:
            return "matview_tome_beauges_476"
        case 1245:
            return "matview_tome_fraiche_aubrac_1245"
        case 516:
            return "matview_tome_tomme_pyrenees_516"
        case 515:
            return "matview_tome_tomme_savoie_515"
        case 443:
            return "matview_valencay_443"
        case _:
            return None




